url: http://twistedminds.creativescapism.com/
name: 'Twisted Minds - a website about serial killers'
description: >
  A website about serial killers and
  psychological disorders

theme: jekyll-theme-cayman